import { useFormik } from "formik";
import { SectionContent } from "../components/CommonEssentials"
import FormFields from "../components/FormFields"
import { useState } from "react";
import { Checkbox, FormControl, FormControlLabel, FormGroup } from "@mui/material";
import { SectionTxt } from "./tc&pp";

const JoinCondition = (props) => {
    const { agreed, setAgreed, onAgree, flowData } = props

    return (
        <>
            <div>
                <div className="btxt">
                    E-COMMERCE VENDOR SERVICES AGREEMENT
                </div>
            </div>
            <div className="sec_container">
                {flowData && flowData.length > 0 && flowData[0].content.map((item) => {
                    return (
                        <SectionTxt
                            title={item.title}
                            description={item.description}
                        />
                    )
                })}
                {/* <div>

                    <div className="sub_sec_txt">
                        This document is an electronic record in terms of the Information Technology Act, 2000 including all its
                        amendments and rules made thereunder as applicable and the amended provisions pertaining to electronic
                        records in various statutes as amended by the Information Technology Act, 2000. This electronic record is
                        generated by a computer system and does not require any physical or digital signatures. A print version of the
                        Agreement is located here and we strongly recommend you keep a print out of this version for your records.
                    </div>
                    <div className="sub_sec_txt">
                        This E-Commerce Services Agreement (hereinafter referred to as “Agreement”) is made on the day of
                        your acceptance of this Agreement from your designated electronic mail address or in any other form of
                        electronic record including, if applicable or provided, clicking on the check box or “I Agree” / “Accept”
                        button or by any other means which construes your acceptance of this Agreement (“Execution Date”)
                        by and between:
                    </div>
                    <div className="sub_sec_txt">
                        You, the details of which are given by you on the Platform on which this Agreement appears, a natural
                        or juristic person competent to enter into valid and legally binding contracts under applicable Indian
                        laws inter alia, a person of legally sound mind, not adjudicated bankrupt and equal to or more than 18
                        (eighteen) years of age as on the Execution Date. If You are a juristic person then the person accepting
                        this Agreement represents that such person is duly authorized by You to bind You to this Agreement
                        and the designated electronic mail address is valid and subsisting and allotted by You to such person
                        (hereinafter referred to as “Merchant” which expression shall unless repugnant to the context and
                        meaning thereof, include its heirs, legal representatives, successors, liquidators, receivers,
                        administrators and permitted assigns), of One Part;
                    </div>
                    <div className="sub_sec_txt">
                        And
                        Basmart Private Limited, a company incorporated under the provisions of the Indian Companies Act,
                        1956 and having its registered office at Pepperfry House, next to UHDE House, Opp. Cipla R&D
                        Centre, Surya Nagar, LBS Road, Vikhroli (West), Mumbai - 400083, Maharashtra, India (hereinafter
                        referred to as “Service Provider” which expression shall unless repugnant to the context and meaning
                        thereof, include its successors, l iquidators and assigns), of Other Part.
                        Merchant and Service Provider shall hereinafter be individually referred to as “Party” and collectively as
                        “Parties”.
                    </div>
                    <ol>
                        <li className="sec_box">
                            <div className="sec_txt">
                                DEFINITIONS
                            </div>
                            <div className="sub_sec_txt">
                                <strong>“Affiliate”</strong> shall mean, with respect to each Party, any person or entity directly or indirectly through one
                                or more intermediary Controlling, Controlled by, or under direct or indirect common Control with a Party.
                                <strong>“Control”</strong>,<strong>“Controlled”</strong> or <strong>“Controlling”</strong> shall mean, with respect to any person or entity, any
                                circumstance in which such person or entity is controlled by another person or entity by virtue of the
                                latter person or entity controlling the composition of the board of directors or managers or owning the
                                largest or controlling percentage of the voting securities of such person/entity or otherwise controlling
                                the other.
                            </div>
                            <div className="sub_sec_txt">
                                “Brand” or “Brand Name” shall mean “TrendSutra™” or “Pepperfry™” or such other successor or
                                replacement brand name / trade mark / service mark as may be decided by the Service Provider upon a
                                prior intimation to the Merchant.
                            </div>
                            <div className="sub_sec_txt">
                                “Confidential Information” means and includes any and all information which is confidential to a Party
                                including any (i) business information and business processes, (ii) any samples, formulations,
                                specifications, data relating to manufacturing and quality control processes and procedures, (iii)
                                advertising and marketing plans, (iv) any past, current or proposed development projects or plans for
                                future development work, (v) technical, marketing, financial and commercial information whether
                                relating to past or current or future, (vi) the commercial and business affairs of a Party, (vi) all customer
                                related information including any rates and discounts, and (vii) and with respect to the Service Provider
                                shall include the End Customer Database.
                            </div>
                            <div className="sub_sec_txt">
                                “Consumer Care Mechanism” means the procedure for resolving customer complaints and grievances,
                                as may be communicated by the Service Provider from time to time, and will include all modifications
                                and amendments thereto.
                            </div>
                            <div className="sub_sec_txt">
                                “Consumer Protection Act” means the Consumer Protection Act, 2019 and the rules and regulations
                                made thereunder, which will include all modifications and amendments thereto.
                            </div>
                            <div className="sub_sec_txt">
                                “Deliverable(s)” shall mean the specific materials, devices, products, services or other deliverables that
                                are provided by the Merchant to the Service Provider during the course of performing the Service
                                Provider Business as per this Agreement and any related document thereto.
                            </div>
                            <div className="sub_sec_txt">
                                “End Customer” shall mean the retail customers to whom the Merchant offers to sell or sells or from
                                whom the Merchant receives offers to purchase the Products through the Platform.
                            </div>
                            <div className="sub_sec_txt">
                                “End Customer Database” shall mean all data/information (as may be updated from time to time) about
                                the persons/entities including their names, addresses, contact details, queries, orders and other
                                requests made available by such persons/entities on the Platform or otherwise captured by the Platform
                                that shall further include the usage, behavior, trends and other statistical information/data relating to
                                such persons/entities, who (i) access the Platform or otherwise get invitation to the Platform or
                                correspond with the Platform, (ii) place any order for Products on the Platform, or (iii) send any enquiry/
                                request with respect to the Platform, and shall include all analysis and records based on such
                                aforementioned information, including the spending and other patterns of such persons/entitles and
                                Products. For the avoidance of doubt, any list, description or other grouping of consumers or customers
                                or any derivative work from End Customer Database shall be deemed to be End Customer Database.
                            </div>
                            <div className="sub_sec_txt">
                                “Service Provider Grievance Officer” shall mean the grievance officer of the Service Provider, as
                                designated by the Service Provider under the Consumer Protection Act.
                            </div>
                            <div className="sub_sec_txt">
                                “Intellectual Property” includes ideas, concepts, creations, discoveries, inventions, improvements, know
                                how, trade or business secrets; trademarks, service marks, domain names, designs, utility models, tools,
                                devices, models, methods, patents, copyright (including all copyright in any designs and any moral
                                rights), masks rights, design right, procedures, processes, systems, principles, algorithms, works of
                                authorship, flowcharts, drawings, books, papers, models, sketches, formulas, teaching techniques,
                                electronic codes, proprietary techniques, research projects, and other confidential and proprietary
                                information, computer programming code, databases, software programs, data, documents, instruction
                                manuals, records, memoranda, notes, user guides; in either printed or machine-readable form, whether
                                or not copyrightable or patentable, or any written or verbal instructions or comments. The End
                                Customer Database shall be considered to be the Intellectual Property of the Service Provider.
                            </div>
                            <div className="sub_sec_txt">
                                “Payment Facilitation Services” shall mean facilitating the receipt of Sale Price on the Platform either
                                along with Platform Services or otherwise (for example cash on delivery services).
                            </div>
                            <div className="sub_sec_txt">
                                “Platform” shall mean the website with a second level domain name / uniform resource locator (URL)
                                bearing the Brand Name with any top level domain name whether presently available for registration or
                                made available for registration at any future date.
                            </div>
                            <div className="sub_sec_txt">
                                “Platform Services” shall mean internet based electronic platform in the form of an intermediary to
                                facilitate sale and purchase of goods and services through the Platform.
                            </div>
                            <div className="sub_sec_txt">
                                “Product(s)” shall mean any and all goods and related services of the Merchant for which the Service
                                Provider makes available the Service Provider Business to the Merchant
                            </div>
                            <div className="sub_sec_txt">
                                “Sale Price” shall be the price at which the Product is offered for sale by the Merchant on the Platform
                                by using the Platform Services to the End Customer. Parties agree that the Sale Price is dynamic and
                                volatile and may vary at different times and points of sale and therefore can be periodically and from
                                time to time changed or revised by the Merchant in accordance with the terms of this Agreement.
                            </div>
                            <div className="sub_sec_txt">
                                “Service Fees” shall mean the fees for availing either whole or part of the Service Provider Business in
                                accordance with the terms of this Agreement and/or Commercial Terms (as defined hereunder).
                            </div>
                            <div className="sub_sec_txt">
                                “Service Provider Business” shall have the meaning as set out Recital 2 hereinabove and shall include
                                Platform, Platform Services, Payment Facilitation Services and Transaction Support Services.
                            </div>
                            <div className="sub_sec_txt">
                                “Service Provider Content” shall mean the Platform, all the pages of the Platform, all the content
                                contained in the Platform (excluding any third party content and advertisements), look and feel of the
                                Platform, any and all information or content owned or controlled (e.g. by license or otherwise) by
                                Service Provider or its Affiliates, including text, images, graphics, photographs, video and audio, and
                                furnished by Service Provider or its Affiliates in connection with Platform Services, Transaction Support
                                Services, Payment Facilitation Services and for the purpose of offering for sale of Products by the
                                Merchant.
                            </div>
                            <div className="sub_sec_txt">
                                “Term” shall have the meaning as set out in Section 13.1 hereto.
                            </div>
                            <div className="sub_sec_txt">
                                “Territory” shall mean the entire world
                            </div>
                            <div className="sub_sec_txt">
                                “Transaction Support Services” shall include services in relation to support the sale of the goods and
                                services by the Merchant to End Customer which shall include product listings, Fulfillment Support
                                Services, logistics management services, customer support services and any other additional services
                                that may be agreed between the parties.
                            </div>
                            <div className="btn btn_primary">
                                Go to Link
                            </div>
                        </li>
                        <li className="sec_box">
                            <div className="sec_txt">
                                INTERPRETATION
                            </div>
                            <div className="sub_sec_txt">
                                In this Agreement, unless the context otherwise requires:
                            </div>
                            <ol>
                                <li className="sub_sec_txt">
                                    Words importing persons or parties shall include natural person, entity, partnership firm,
                                    organization, operation, Company, HUF, voluntary association, LLP, joint venture, trust, limited
                                    organization, unlimited organization or any other organization having legal capacity;
                                </li>
                                <li className="sub_sec_txt">
                                    Words importing the singular shall include the plural and vice versa, where the context so requires;
                                </li>
                            </ol>
                        </li>
                    </ol>
                </div> */}

                <div className="sub_sec_txt sec_row">
                    <FormControl component="fieldset">
                        <FormGroup aria-label="position" row>
                            <FormControlLabel
                                value="top"
                                control={<Checkbox checked={agreed}
                                    onChange={onAgree} name={"IAgree"}
                                />}
                                label="I Agree to the Terms and Conditions"
                                labelPlacement="right"
                            />
                        </FormGroup>
                    </FormControl>
                </div>
            </div>
        </>
    )
}

export default JoinCondition